=== thenodon/bisdw/src/main/resources/bisdw.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="bisdw">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="etljob" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="etljob">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="name" minOccurs="1" maxOccurs="1" />
				<xsd:element ref="desc" minOccurs="0" maxOccurs="1" />
				<xsd:element ref="schedule" minOccurs="1" maxOccurs="unbounded" />
				<xsd:element ref="etlconfig" minOccurs="1" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="etlconfig">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="desc" minOccurs="0" maxOccurs="1" />
				<xsd:element ref="class" minOccurs="1" maxOccurs="1" />
				<xsd:element ref="order" minOccurs="0" maxOccurs="1" />
				<xsd:element ref="property" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
			<xsd:attribute name="name" type="xsd:string" use="required" />
		</xsd:complexType>
	</xsd:element>


	<xsd:element name="name" type="xsd:normalizedString" />
	<xsd:element name="desc" type="xsd:string" />
	<xsd:element name="schedule" type="xsd:normalizedString" />

	<xsd:element name="property">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="key" />
				<xsd:element ref="value" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

    <!-- Sort order is lower value executed first. A lack of order value is regarded as 0 -->
    <xsd:element name="order" nillable="true" type="xsd:nonNegativeInteger" />
    
	<xsd:element name="class" type="xsd:normalizedString" />
	<xsd:element name="key" type="xsd:normalizedString" />
	<xsd:element name="value" type="xsd:normalizedString" />


</xsd:schema>

=== thenodon/bisdw/etc/bisdw.xml
<?xml version="1.0" encoding="UTF-8"?>
<bisdw xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../src/main/resources/bisdw.xsd">
	<etljob>
		<name>read_DB</name>
		<desc>Database</desc>
		<schedule>0 */1 * * * ?</schedule>

		<etlconfig name="read_db">
			<desc>read db</desc>
			<class>com.ingby.socbox.bisdw.etlprovider.ETLScriptella</class>
			<order>10</order>
			<property>
				<key>configFile</key>
				<value>read_db.xml</value>
			</property>
		</etlconfig>

	</etljob>




</bisdw>
